#!/usr/bin/env python3

# This script generates the list of words considered valid by SpellingBeat.
#
# It requires two files as input:
#   - answers.log: a log of all the Spelling Bee answers to date (generated by collect_answers.py)
#   - nwl2020.txt: the official NASPA Scrabble word list (licensed for non-commercial use)
#
# The script first filters the official word list, removing any words that are not valid for
# Spelling Bee (e.g. words that are too short, contain an 's', or contain more than seven unique
# characters). It then iterates through the answers, generating all possible valid words for each
# day's letters and subtracting those from the official word list to find the words that the NYT
# has excluded. It also finds any words that the NYT has added that aren't in the official word
# list. The result is written out to words-filtered.

import os
import re

# this script is meant to be run from the root directory of the project
rootdir = os.path.join(os.path.dirname(os.path.realpath(__file__)), '..')
datadir = os.path.join(rootdir, "data")

# read the NASPA word list
with open(os.path.join(datadir, "nwl2020.txt")) as f:
    nwl_words = f.read().strip().split("\n")

# filter out invalid words
nwl_words = set([w for w in nwl_words if len(w) >= 4 and 's' not in w and len(set(w)) <= 7])

# join the words into a single string for regex matching
nwl_words_str = " ".join(nwl_words)

# read the answers log and generate the list of all valid words
all_answers = set()
all_excludes = set()

with open(os.path.join(datadir, "answers.log")) as f:
    answers_log = f.readlines()

for line in answers_log:
    date, letters, answers = line.strip().split(" ")
    answers = set(answers.split(","))
    all_answers |= answers

    # we generate all valid words and then subtract the answers to get the words the NYT excluded
    pattern = '\\b[' + letters + ']*' + letters[0] + '[' + letters + ']*\\b'
    matches = set(re.findall(pattern, nwl_words_str))
    excluded = matches - answers
    all_excludes |= excluded

# generate the final word list by subtracting the excluded words from the official word list,
# then adding in the answers
all_words = nwl_words - all_excludes | all_answers

# output the final word list as a single space-separated string
with open(os.path.join(datadir, "words-filtered"), "w") as f:
    f.write(" ".join(sorted(all_words)))

# output the excluded words for spot-checking
with open(os.path.join(datadir, "excluded-words"), "w") as f:
    f.write("\n".join(sorted(all_excludes)))

# output the included words for spot-checking
all_includes = all_answers - nwl_words
with open(os.path.join(datadir, "included-words"), "w") as f:
    f.write("\n".join(sorted(all_includes)))

